defaults:
  - finetune

handler: GradDiff
method_args:
  gamma: 1.0
  alpha: 1.0
  retain_loss_type: NLL
  optimizer_name: null
  optimizer_kwargs:
    muon_momentum: null
    muon_ns_steps: null
    muon_adjust_lr_fn: null
    muon_lr: null
    muon_weight_decay: null
    adamw_lr: null
    adamw_betas: null
    adamw_weight_decay: null
    adamw_eps: null
